### ISSUE TITLE
Error generating reports

### ISSUE THREAD

**Issue by eirinnm** [valenlab/amplican#2]
Hi! I have Amplican installed in R 3.3.1 with Anaconda under Windows 10. The example pipeline works up until the generation of the reports. 

I launched it with this command: `amplicanPipeline(config,fastq_folder, "results")`

This is the error:

```
Quitting from lines 14-19 (report_id.Rmd)
Error in file(file, "rt") : cannot open the connection
In addition: Warning message:
In file(file, "rt") :
  cannot open file 'results/alignments_events.csv': No such file or directory
```

I think it's because the CSV files are in **results/** while the Rmd files are in **results/reports**, so when the Rmd file refers to results/alignments_events.csv, it points towards a relative path that doesn't exist.

I fixed it by manually editing the Rmd files, changing results_folder (on line 14) to '..' so that the assembled path is now results/reports/../alignment_events.csv. Then it works when I call rmarkdown::render. I guess the real fix is somewhere in helpers_rmd.R.

Also: I get an error when rendering report_amplicon.Rmd:

```
Quitting from lines 214-215 (report_amplicon.Rmd)
Error in mapply(child_vp, vp_name = vpname(x$layout), t = x$layout$t,  :
  zero-length inputs cannot be mixed with those of non-zero length
```

I hope you can get these issues fixed soon, as I'm looking forward to using Amplican on our miseq data!

**Comment by JokingHero** [comment]
Hi, 

Sorry to keep you waiting for so long, but there have been even more problems than we realized. I am working on that. 
To relate to your first error, this should be always the full path to the folder where you want to store the results. 
Second error is unfortunately not up to us, we still have to wait for [this issue](https://github.com/tengfei/ggbio/issues/85), so that it can be resolved. 

Our problems come mainly from the fact that we are not included yet in the bioconductor life-cycle and with latest bioconductor update, many packages broke our amplican. We did not get informed of changes as we are not included yet. I will try to figure out a workarounds by the end of this week. Please be patient.

**Comment by JokingHero** [comment]
It should be fixed now.
